structure(list(id = structure(0x1.2eeedfp-1050, class = "integer64"), 
    upi = "URS00012EEEDF", timestamp = structure(0x1.7794404053acdp+30, class = c("POSIXct", 
    "POSIXt"), tzone = "UTC"), userstamp = "rnacen", crc64 = "C13030A126A9D7FB", 
    len = 493L, seq_short = "AAAGGAATAGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTCAATTCGACGCAACGCGAAGAACCTTACCCAGGCTCGAACGGCAAGAGACCTCCGGCGAAAGCCGGCTCCCGCAAGGGCTGTTGTCGAGGTGCTGCATGGCTGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTGTCCTCTGTTGCCATCAAGTCAAGTTGGGCACTCTGAGGAGACTGCCGGTGATAAACCGGAGGAAGGTGGGGATGACGTCAAGTCAGCATGGCCTTTATGTCTGGGGCTACACACGTGCTACAATGGCCGACACAAACCGTCGCGATGCCGCAAGGTGGAGCTAATCGGACAAAGTCGGTCTCAGTTCGGATTGCAGGCTGCAACTCGCCTGCATGAAGTTGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGT", 
    seq_long = NA_character_, md5 = "61d81ee99bbeb73d526feb4f6a3294d3"), row.names = c(NA, 
-1L), class = "data.frame")
