# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Print tables iteratively
#'
#' @description
#' This function takes a list of `flextable` or `kableExtra` objects and prints the raw code adapted to the 'output'
#' format. \strong{Note} that chunk option results must be set to \strong{asis}, i.e., `results='asis'`.
#'
#' @param l A list of `flextable` or `kableExtra` objects, which are s3 lists with certain structures.
#' @param output A string specifying the output format.
#'
#' @return Invisible.
#'
#' @importFrom flextable flextable_to_rmd
#' @importFrom flextable autofit
#' @export
#'
#' @examples
#' \donttest{
#' # Toplines to word
#' print_tbls(list_toplines, output = "word")
#'
#' # Crosstabs to pdf
#' print_tbls(list_xtabs, output = "pdf")
#' }
print_tbls <- function(l, output) {
    invisible(.Call(`_citizenr_print_tbls`, l, output))
}

